<?php

/**
 * PluginCatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCat');
    }
}