<?php

/**
 * PluginInfosRestoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginInfosRestoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginInfosRestoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginInfosResto');
    }
}