<?php

/**
 * PluginRestaurantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginRestaurantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginRestaurantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginRestaurant');
    }
}