<?php

/**
 * PluginTypeCatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTypeCatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTypeCatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTypeCat');
    }
}