<?php

/**
 * PluginCarteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCarteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCarteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCarte');
    }
}