<?php

/**
 * PluginPlatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPlatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPlatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPlat');
    }
}