<?php

/**
 * PluginDailyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDailyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDailyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDaily');
    }
}